# 3 Виконання

## 3.1 Генерування випадкових і невипадкових масивів різними способами, зазначеними в теоретичних відомостях.

### Імпортуємо модуль NumPy та покажумо різні можливості створення масивів.

### Покажемо модливість створення цілочисельної матриці 3х3.

In [1]:
import numpy as np
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

*Створення матриці 3х3*

### Покажемо можливість створення матриці різних типів, наприклад, float та int.

In [3]:
a_int = np.array([1, 2, 3, 4], dtype='float')
a_float = np.array([1, 2, 3, 4], dtype='int32')
print(a_int)
print(a_float)

[1. 2. 3. 4.]
[1 2 3 4]


*Створення масивів типів float та int32*

### NumPy має можливість автоматичного створення масивів, покажемо це.

### Покажемо можливість створення масиву, задаючи початкове, кінцеве значення та крок.

In [4]:
np.arange(1,8,3)

array([1, 4, 7])

*Створення масиву, де початок - 1, кінець - 8, крок - 3*

### Продемонструємо можливість створення масиву цілочисельних одиниць за допомогою методу ones.

In [5]:
np.ones(9, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

*Одновимірний масив одиниць з 9-ти елементів*

### Продемонструємо можливість створення двовимірного масиву нулів за допомогою методу zeros.

In [6]:
np.zeros((3, 4), dtype='float')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

*Матриця 3х4 нулів типу float*

### Створимо масив з 6-ти значень, що рівномірно розподілені між 0 та 1.

In [12]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

*Одновимірний масив з шести значень, що рівномірно розподілені між 0 а 1*

### Створимо масив 4х4 з рівномірно розподілених випадкових чисел від 0 до 1.

In [13]:
np.random.random((4, 4))

array([[0.13033435, 0.74283195, 0.68012242, 0.10431953],
       [0.9159478 , 0.24454688, 0.86073132, 0.78828324],
       [0.94786684, 0.34052187, 0.75032444, 0.4807424 ],
       [0.57201738, 0.75682698, 0.33011881, 0.1185312 ]])

*Масив 4х4 з рівномірно розподілених випадкових чисел від 0 до 1*

### Створимо матрицю 4х2 випадкових цілих чисел від -10 до 10. Для цього використаємо метод numpy.random.randint.

In [15]:
np.random.randint(-10, 10, (4, 2))

array([[ -5,   4],
       [-10,   4],
       [  6,  -6],
       [ -4,   2]])

*Матриця 4х2 випадкових цілих чисел від -10 до 10*

### Створимо масив з 7-ми порожніх елементів, у яких буде випадковий вміст комірок пам'яті.

In [16]:
np.empty(5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

*Масив з 7-ми порожніх елементів*

## 3.2 Демонстація звернення до елементів масиву за допомогою індексів, в тому числі від’ємних; виділення підмасивів як одновимірних, так і багатовимірних масивів

### Покажемо доступ елементів за індексом. Створимо масив елементів, передаючи список цілих чисел. Знайдемо другий елемент масиву.

In [19]:
a = np.array([1, 2, 3, 4, 5, 6])
a[1]

2

*Другий елемент масиву*

### Знайдемо останній елемент масиву.

In [20]:
a[-1]

6

*Останній елемент масиву*

### Створимо матрицю, передавши список списків цілих чисел. Виділимо одновимірний підмасив, передавши індекс 0 та : для захвати усіх чисел рядка.

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[0, :]

array([1, 2, 3])

*Перший рядок матриці*

### Виділимо двовимірний підмасив, передавши проміжок рядків :2 та стовпців :2.

In [22]:
a[:2, :2]

array([[1, 2],
       [4, 5]])

*Матриця 2х2 з перших двох елементів перших двої рядків*

## 3.3 Демонстація основних арифметичних операцій над масивами, а також роботи методів reduce, accumulate, outer.